feat(ui): Create CourseProgressComponent (#64)
CodersCrew/coderscamp pull request #146
Opened 2021-08-12 18:22 UTC by lagdush

2021-08-13 15:10 UTC, KonradSzwarc requested changes

2021-08-13 15:10 UTC, KonradSzwarc commented on packages/ui/src/components/CourseProgressCard/CourseProgressCard.tsx
> +                <Typography as="p" weight="medium" size="sm" color="gray.900">
🤔 There should be 4px of margin bottom

2021-08-13 15:10 UTC, KonradSzwarc commented on packages/ui/src/components/CourseProgressCard/CourseProgressCard.tsx
> +              <Progress value={value.value} max={value.max} />
🤔 There should be 2px of border radius

2021-08-13 15:10 UTC, KonradSzwarc commented on packages/ui/src/components/CourseProgressCard/CourseProgressCard.tsx
> +type Stats = Statistic[];
🙃 As you use it only once maybe there is no need to create this type

2021-08-13 15:10 UTC, KonradSzwarc commented on packages/ui/src/components/CourseProgressCard/CourseProgressCard.stories.tsx
> +const status = [
🙃 You can name it `statsData` and re-export to tests so you wouldn't duplicate mocks

2021-08-14 17:46 UTC, Veryyapeee approved these changes

2021-08-15 11:00 UTC, KonradSzwarc approved these changes

2021-08-16 12:43 UTC, merged