feat(website): create LearningSources section (#95)
CodersCrew/coderscamp pull request #148
Opened 2021-08-12 20:49 UTC by KonradSzwarc

Closes #95

2021-08-13 14:20 UTC, lagdush requested changes

2021-08-13 14:20 UTC, lagdush commented on packages/website/src/components/LearningSources/LearningSources.tsx
> +            Czym jest CodersCamp?
🤔 I think it should be here: "Skąd będziesz czerpać wiedzę"

2021-08-14 10:41 UTC, KrystianKjjk approved these changes

2021-08-14 12:52 UTC, lagdush approved these changes

2021-08-15 11:04 UTC, merged