feat: Create badge component
CodersCrew/coderscamp pull request #16
Opened 2021-06-23 17:33 UTC by hoolek77

- Main badge configuartion:
  - size: large or small
  - colors: each one matches mockups
  - variants: default, solid, or outlined (The default one matches mockups. Rest wasn't included in them, but I've decided to leave it anyway, just in case we need them in the future)
- PR also contains stories with playground and some basic tests

2021-06-28 16:15 UTC, KonradSzwarc requested changes

2021-06-28 16:15 UTC, KonradSzwarc commented on packages/ui/src/components/Badge/Badge.tsx
> +  variant?: BadgeVariant;
The badge shouldn't receive variant property. We don't know if we will use other variants of this component in the future so this property adds unnecessary complexity.

2021-06-28 16:15 UTC, KonradSzwarc commented on packages/ui/src/components/Badge/Badge.tsx
> +  onClick?: ChakraBadgeProps['onClick'];
For now, the badge shouldn't be clickable

2021-06-28 16:15 UTC, KonradSzwarc commented on packages/ui/src/components/Badge/Badge.tsx
> +        {...(size === 'small' ? { ...smallStyleProps } : { ...largeStyleProps })}
It could more readable if you move the result of this conditional to a separate variable and only destructure it here

2021-06-28 16:15 UTC, KonradSzwarc commented on packages/ui/src/components/Badge/Badge.test.tsx
> +    const badge = screen.getByTestId('badge');
I think that `screen.getByText` will be a more suitable method to catch the Badge component. There is probably no need for the `data-testid` attribute here.

2021-06-28 16:18 UTC, KonradSzwarc commented
I looked to the Storybook and badges mostly match mockups but there is one flaw. In Storybook Badge text is always written uppercase when in mockups it has a normal capitalization.
<img width="413" alt="CleanShot 2021-06-28 at 18 15 46@2x" src="https://user-images.githubusercontent.com/22938071/123669940-f087c880-d83c-11eb-9387-5c3395f6859b.png">

2021-06-28 21:25 UTC, KonradSzwarc requested changes

2021-06-28 21:25 UTC, KonradSzwarc commented on packages/ui/src/components/Badge/Badge.tsx
> +      colorScheme={color}
When `color` prop is equal to `'default'` you need to pass `gray` as the `colorScheme`. Currently, for the default badge, you have this CSS
![CleanShot 2021-06-28 at 23 19 55@2x](https://user-images.githubusercontent.com/22938071/123705550-699c1580-d867-11eb-95de-a3b689fc22a1.png)

2021-06-28 21:25 UTC, KonradSzwarc commented on packages/ui/src/components/Badge/Badge.tsx
> +  const sizeProps = size === 'small' ? { ...smallStyleProps } : { ...largeStyleProps };
I think there is no need to destructure `smallStyleProps` and `largeStyleProps` just to create an object from them again.

2021-06-28 21:25 UTC, KonradSzwarc commented on packages/ui/src/components/Badge/Badge.stories.tsx
> +    <Badge size="small" color="red">
A small thing, but if we want to show how the component displays with different `size` prop, we shouldn't pass other props like `color`. I think you can just leave the default value here.

2021-06-28 21:25 UTC, KonradSzwarc commented on packages/ui/src/components/Badge/Badge.stories.tsx
> +    <Badge size="small" color="red">
A small thing, but if we want to show how the component displays with different `size` prop, we shouldn't pass other props like `color`. I think you can just leave the default value here.

2021-06-28 21:27 UTC, KonradSzwarc commented on packages/ui/src/components/Badge/Badge.test.tsx
> +    expect(badge).toBeVisible();
When you want to check if an element correctly renders in the DOM it's recommended to use the `toBeInTheDocument` method

2021-06-28 21:43 UTC, KonradSzwarc approved these changes

2021-06-29 16:17 UTC, KrystianKjjk approved these changes

2021-06-29 18:06 UTC, merged