add draft sidebar, sidebarItem and stories for them
CodersCrew/coderscamp pull request #163
Opened 2021-08-16 16:24 UTC by kamildzierzak

2021-08-18 19:46 UTC, KrystianKjjk commented
If "Navbar" component is website feature, sidebar shouldn't be on the website side too? 🤔

2021-08-19 20:44 UTC, KonradSzwarc commented
> If "Navbar" component is website feature, sidebar shouldn't be on the website side too? 🤔

Maybe not website but it should be on the panel side

2021-08-28 17:02 UTC, lagdush commented on packages/ui/src/components/SidebarItem/SidebarItem.test.tsx
> +    expect(sidebarItem).toHaveStyle({ pointerEvents: 'none', opacity: '0.6' });
At the moment we are testing if the element gets the right style. Maybe a better solution is to check if it gets the disabled attribute? As I checked, toBeDisabled () doesn't work here, toHaveAttribute ('disabled') works instead, but you have to block this line for eslint. @KonradSzwarc which solution is better?

2021-09-22 12:30 UTC, hoolek77 requested changes
🙃  The sidebar item with the icon is missing some margin-left. Rest looks good for me 👏🏻.

2021-09-23 11:27 UTC, hoolek77 approved these changes
Looks good to me! ✅

2021-09-23 19:29 UTC, lagdush approved these changes

2021-09-23 20:23 UTC, merged