Feature sign up page for candidates
CodersCrew/coderscamp pull request #23
Opened 2021-06-29 13:28 UTC by lagdush

I think the component is ready. When the Logo and Button components are ready, we need to add them.
close #1

2021-07-05 16:05 UTC, talcia submitted a review, later dismissed

2021-07-11 20:38 UTC, KonradSzwarc requested changes
I think you can replace our test counter button with your views. This way it would be possible to look at the views in the preview environment

2021-07-21 19:48 UTC, KonradSzwarc requested changes
As we use Yarn, there shouldn't be package-lock.json in the repository

2021-07-23 09:11 UTC, KonradSzwarc submitted a review, later dismissed

2021-07-24 13:46 UTC, kamildzierzak approved these changes

2021-07-25 08:33 UTC, KonradSzwarc approved these changes

2021-07-25 13:51 UTC, merged