fix(website): bigger dots in horizontal nav (#206)
CodersCrew/coderscamp pull request #240
Opened 2021-08-27 19:42 UTC by kamildzierzak

Closes #206

2021-08-28 07:42 UTC, wierzbka10 reviewed
Every dot and icon button shoud be in frame whic
![dots navigation](https://user-images.githubusercontent.com/46423273/131210603-9ce366f0-d3eb-4de5-ad34-ffa57ec04b8a.png)
h has 40x40px

2021-08-28 14:17 UTC, Veryyapeee requested changes
As @wierzbka10 said, the arrow button is currently 32x32px ~ we need to change that

2021-08-30 13:48 UTC, KrystianKjjk approved these changes

2021-08-30 16:01 UTC, Veryyapeee approved these changes

2021-08-30 16:17 UTC, wierzbka10 requested changes
On mobile screens where dots navigation don't fit in width, it should change to number pagination just like in the projects.
![Screenshot_2021-08-30-17-13-25-034_com android chrome](https://user-images.githubusercontent.com/46423273/131370953-7dff1638-777a-444d-b205-6bfb6aeadd3a.jpg)
![Screenshot_2021-08-30-17-40-45-005_com android chrome](https://user-images.githubusercontent.com/46423273/131370956-7add9f4c-ca25-44e7-aa18-1fd47523bf60.jpg)

2021-09-15 10:37 UTC, wierzbka10 approved these changes

2021-09-15 10:38 UTC, merged