fix: mobile menu is too small (#204)
CodersCrew/coderscamp pull request #246
Opened 2021-08-28 19:23 UTC by lagdush

Closes #204

2021-08-29 21:06 UTC, KonradSzwarc requested changes
There are a few problems with the current design:
1. Items don't look like they are clickable.
2. Items don't interact with the cursor. There is no pointer when you hover them, and they don't change their styles on hover.
3. Items are not focusable when you press Tab, or at least it's not visible that they are focusable.
4. The close button is too close to the left side.
5. If the current page is clickable (as it is now), it shouldn't have a distinguished styling. If the current page has a distinguished styling (as it has now), it shouldn't be clickable.

<img width="585" alt="CleanShot 2021-08-29 at 23 01 02@2x" src="https://user-images.githubusercontent.com/22938071/131265225-709c5a43-37da-4ef1-977d-aa222f15150c.png">

2021-08-29 21:06 UTC, KonradSzwarc commented on packages/website/src/components/Navbar/BaseNavbar.tsx
> +  const iconButonSize = 'md';
💭 I'm not sure if there is a need for this constant. In theory menu open and close buttons are separate components and doesn't have to share the same size

2021-09-03 10:06 UTC, wierzbka10 requested changes
I designed menu on mobile :) On every screens smaller than 560px wide buttons "zapisz się na kurs" and "zostań mentorem" are inside drop-down menu, but on screens bigger or equel than 560px the buttons are in the navigation, not in the menu. Remember about hover and focus states. 

Link to figma: https://www.figma.com/file/ur0KLA9ZOtiodrAmpXrxh9/CodersCamp-app-and-website?node-id=2804%3A9699

2021-09-04 16:17 UTC, wierzbka10 requested changes
You forgot about focus state on the clickable elements, now is only on buttons.

2021-09-06 10:34 UTC, wierzbka10 requested changes
Focus state on clickable elements in menu shoud appear only when you move by tab like on the buttons

2021-09-06 17:42 UTC, wierzbka10 approved these changes

2021-09-06 17:44 UTC, hoolek77 approved these changes

2021-09-06 18:11 UTC, KonradSzwarc approved these changes

2021-09-06 18:12 UTC, merged