refactor: prepare the project to use custom icons (#40)
CodersCrew/coderscamp pull request #42
Opened 2021-07-07 18:53 UTC by hoolek77

Closes #40

2021-07-07 19:26 UTC, KonradSzwarc commented on .github/workflows/workflow.yml
> +      - name: generate workspaces
As this command doesn't generate new workspaces I think "create autogenerated content" could be a better name

2021-07-08 17:52 UTC, mecies approved these changes
LGTM, please correct the typo ✅ 
I recommend **cSpell** `streetsidesoftware.code-spell-checker` extension to prevent such situations.

2021-07-08 17:52 UTC, mecies commented on .github/workflows/workflow.yml
> +      - name: tsc compile webside
You probably meant `website` 😄

2021-07-09 10:17 UTC, mecies approved these changes
Looks good to me ✅ 
Please keep in mind that I'm not fully onboarded and I do not know project dependencies etc, code looks good 😄

2021-07-09 19:36 UTC, KonradSzwarc approved these changes

2021-07-09 19:37 UTC, KonradSzwarc requested changes
Something with Heroku is broken. I will investigate it

2021-07-09 20:18 UTC, KonradSzwarc commented
Ok, I got the problem
<img width="1113" alt="CleanShot 2021-07-09 at 22 17 40@2x" src="https://user-images.githubusercontent.com/22938071/125131745-88ba6300-e103-11eb-91c1-ea405fe86a12.png">

2021-07-09 21:08 UTC, KonradSzwarc approved these changes

2021-07-10 13:18 UTC, lagdush approved these changes

2021-07-10 14:32 UTC, merged