feat(ui): radio component
CodersCrew/coderscamp pull request #46
Opened 2021-07-07 20:47 UTC by kacper-cyra

Added radio input element with stories and a test.

Closes #30

2021-07-08 19:04 UTC, KonradSzwarc requested changes

2021-07-08 19:04 UTC, KonradSzwarc commented on packages/ui/src/components/Radio/Radio.tsx
> +export const Radio = forwardRef<RadioProps, 'div'>(
In Chakra `ref` is passed to the `input` element

2021-07-08 19:04 UTC, KonradSzwarc commented on packages/ui/src/components/Radio/Radio.tsx
> +  ({ color = 'default', value, children = '', checked = false, disabled = false, size = 'md', ...props }, ref) => {
I think there is no need to destructure the `children` property

2021-07-08 19:26 UTC, kacper-cyra commented on packages/ui/package.json
> +    "ts-node": "10.0.0"
When I tried to run yarn test, jest displayed error that he cannot compile jest.config.ts without ts-node dependency installed.

2021-07-09 19:31 UTC, KonradSzwarc commented on packages/ui/src/components/Radio/Radio.tsx
> +export type RadioColor = 'default' | 'brand';
as unknown as string

2021-07-09 19:31 UTC, KonradSzwarc submitted a review, later dismissed

2021-07-09 21:52 UTC, KonradSzwarc commented on packages/ui/package.json
> +    "ts-node": "10.0.0"
Sounds legit, but if that's the case install `ts-node` in the root folder as we use jest in all workspaces

2021-07-09 21:56 UTC, KonradSzwarc commented on packages/ui/src/components/Radio/Radio.tsx
> +      <ChakraRadio
A small thing, but Radio should have a different color when use is clicking it (active state, third row on mockups). You can use [theme component syles](https://chakra-ui.com/docs/theming/component-style), to apply it

2021-07-10 13:04 UTC, Veryyapeee commented on packages/ui/src/components/Radio/Radio.tsx
> +  disabled?: boolean;
I think we should comment the code only when it's that complicated that it can't speak for itself

2021-07-10 13:04 UTC, Veryyapeee commented on packages/ui/src/components/Radio/Radio.tsx
> +    return (
"=> (<ChakraRadio />) - simpler version

2021-07-10 17:18 UTC, KonradSzwarc requested changes

2021-07-10 17:18 UTC, KonradSzwarc commented on packages/ui/src/theme/overwrites/components/radio.ts
> +      border: '6px solid brand.700',
Shouldn't you modify only the `borderColor` property here?

2021-07-10 17:18 UTC, KonradSzwarc commented on packages/ui/src/theme/overwrites/index.ts
> +  components: { ...components },
There is no need to destructure `components` to a new object. You can just pass them as `styles` are passed

2021-07-10 17:18 UTC, KonradSzwarc commented on packages/ui/src/components/Radio/Radio.tsx
> +export type RadioSize = 'md' | 'lg';
There is no need to export this type as we don't use it anywhere else

2021-07-10 17:23 UTC, kacper-cyra commented
I added the styling for pseudo classes, but encounter problems with :active. I made it work properly through normal css but in chakra it does not apply at all, no matter what browser.

2021-07-10 21:01 UTC, KonradSzwarc approved these changes

2021-07-11 10:33 UTC, hoolek77 approved these changes

2021-07-11 11:18 UTC, merged