refactor(ui): Button component Closes #9
CodersCrew/coderscamp pull request #71
Opened 2021-07-19 21:38 UTC by talcia

2021-07-20 14:28 UTC, KonradSzwarc requested changes

2021-07-20 14:28 UTC, KonradSzwarc commented on packages/ui/src/theme/overwrites/components/button.ts
> +        width: '13.33px',
🤔 Shouldn't it be 16px?

2021-07-20 21:21 UTC, hoolek77 approved these changes

2021-07-21 11:09 UTC, kamildzierzak approved these changes

2021-07-21 19:38 UTC, KonradSzwarc approved these changes

2021-07-26 16:23 UTC, merged